Repository kilicf/loruki-website, pull requests merged in 2021-02, with the labels that each got.

#2 PR zehrayelkenci
  README.md
  planning/backlog.md
  planning/development-strategy.md
Labels: documentation

#14 Edit feature html file
  features.html
Labels: enhancement

#15 PR for wireframe
  planning/development-strategy.md
  planning/imeges/New Wireframe 1.png
Labels: documentation

#21 zehra.doc.update
  CSS/style.css
  CSS/utilities.css
  css/style.css
  css/utilities.css
  docs.html
  images/Lokurimainpage.png
Labels: css, html
